#!/bin/sh

# -I/usr/local/cc65-bbc/lib/cc65/include
export CC65_INC=/usr/local/cc65-bbc/lib/cc65/include
export LD65_LIB=/usr/local/cc65-bbc/lib/cc65/lib
export LD65_OBJ=/usr/local/cc65-bbc/lib/cc65/lib
export LD65_CFG=/usr/local/cc65-bbc/share/doc/cc65

## This combination does not work!
# cc65 test.c &&
# ca65 -l -t bbc test.s &&
# ld65 -t bbc -o test test.o bbc.lib

cl65 -t bbc -o test test.c
cc65 test.c ## generate the .s for interest

## Deploy
cp -f ./test ../mycode.conv/test

